language: elixir
elixir: '1.9'

before_script:
  - y | mix local.rebar
script:
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)